### ISSUE TITLE
Secrets is not work 

### ISSUE THREAD

**Issue by hatavan83** [josmo/drone-k8s-deployment#6]
Hi josmo,
I use Drone CI 0.8.xx, when I try config pipeline with `secrets`, it is always fails :(
The `url` and `token` attributes are always required when I try use with `secrets: [kubernetes_url, kubernetes_token]` that mapping with  `KUBERNETES_URL`, `KUBERNETES_TOKEN` on Secrets menu of Drone CI. Could you please give me more detail about config secrets for this plugin?

False example:
```
pipeline:
  deploy:
    image: peloton/drone-k8s-deployment
    insecure: false
    deployment_names: [mything, mything2]
    container_names: mything
    namespaces: [mynamespace, anothernamspace]
    docker_image: drone/drone:latest
    date_label: deployment.drone.io/date-deployed
    secrets: [kubernetes_url, kubernetes_token]
```
